// boss.js — BOSS 立绘(重画:grid 内只含 legend 字符与点,16×16 正方形避免拉伸)
import { makeSprite } from './_tools.js';
import { PAL } from '../palette.js';

// 守林人:树冠头 + 凹眼 + 树干身 + 根
const L_forest_boss = {
  '.': null, 'k': PAL.black,
  'g': '#6fb872', 'G': '#3a5a3a', 'l': '#a8e8b0',
  'b': '#4a3528', 'B': '#2a1a14', 's': '#3a4a3a', 'S': '#2a3a2a',
  'e': '#0a1a0a', 'w': '#e0e8c0', 'm': '#3a3a4a',
};
export const FOREST_BOSS = makeSprite(`
....kkkkkkkk....
...kgggggggk....
..kgllllllllgk..
..kgllllllllgk..
..kgleelleelgk..
..kgllllllllgk..
..kgllllllllgk..
..kgllllllllgk..
...kgllllllgk...
....kgggggk.....
....kbbbbk......
...kbbbbbbk.....
..kbbBbBbbk.....
..kbbbbbbbk.....
..kbbbbbbbk.....
..kkkkkkkkkk....`, L_forest_boss, 6);

// 焚身王:王冠 + 火焰头身 + 双眼 + 红王袍
const L_fire_boss = {
  '.': null, 'k': PAL.black,
  'e': '#e87a3c', 'E': '#8a3a1a', 'l': '#ffc060',
  'r': '#c14d4d', 'R': '#6a2a1a', 'g': '#e0b76a',
  'b': '#3a1a1a', 'w': '#f4e8c0', 's': '#5a3a2a',
};
export const FIRE_BOSS = makeSprite(`
...kgggggggk....
..keeeeeeeeek...
..keellllleek...
.keeellllleek...
.kellleeeelllek
.kellweeeewllk..
.kellleeeelllk..
..kelllllllek...
..kerrrrrrrrek..
.kerrrRRRrrrek..
.kerrrrrrrrek...
.kerrrRRRrrrek..
.kerrrrrrrrek...
.kerrrrrrrrek...
.keeerrrrreek...
..kkkkkkkkkkk...`, L_fire_boss, 6);

// 编年者:尖帽法师 + 长袍 + 钟盘金纹
const L_chrono = {
  '.': null, 'k': PAL.black,
  'i': '#4a3a6a', 'I': '#2a1a3a', 'w': '#d6c8a4', 'W': '#a89474',
  'l': '#8a7ab0', 'e': '#0a0a0a', 'g': '#e0b76a',
};
export const CHRONO_BOSS = makeSprite(`
......kk.......
.....kIIk......
....kIIIIk.....
...kIiiiiIk....
...kIiiiiIk....
...kIseeeIk....
...kIssssIk....
...kIIIIIIk....
..kIiiiiiiIk...
..kIiggggiIk...
..kIigllgiIk...
..kIiggggiIk...
..kIiiiiiiIk...
..kIIIIIIIIk...
..kIik..kIIk...
...kkk..kkk....`, L_chrono, 6);

// 寂渊:虚空多眼 + 触手(诡异破碎的最终存在)
const L_void_boss = {
  '.': null, 'k': PAL.black,
  'v': '#3a2a4a', 'V': '#1a0a2a', 'l': '#b78ce0', 'L': '#e0b0ff',
  'm': '#a8b8d0', 'M': '#5a6a8a', 'e': '#0a0a14',
  'w': '#f4ecd0', 's': '#5a4a6a',
};
export const FORGOTTEN_BOSS = makeSprite(`
...kkkkkkkkk...
..kvvvvvvvvvk..
..kvLLLLvLLvk..
.kvLLLLvLLLvk..
.kvvvvvvvvvvk..
.kvvlvvvvvlvk..
.kvvvvvvvvvvk..
.kvvlvvvvvlvk..
.kvvvvvvvvvvk..
.kvvlvvvvvlvk..
.kvvvvvvvvvvk..
.kvvlvvvvvlvk..
.kvvvvvvvvvvk..
..kvvvvvvvvk..
..kkkkkkkkkk...`, L_void_boss, 6);
