// enemies.js — 通用敌人精灵(重画:闭合轮廓、明确身份、grid 内只有 legend 字符与点)
// 规则:grid 模板字符串内严禁空格/中文(会被当成像素数据)。说明写在 grid 外的 // 注释。
import { makeSprite } from './_tools.js';
import { PAL } from '../palette.js';

// 森林光精灵:圆球 + 大白眼黑瞳
const L_forestSpirit = {
  '.': null, 'k': PAL.black, 'K': '#0a1a14',
  'g': '#6fb872', 'G': '#3a5a3a', 'l': '#a8e8b0',
  'w': '#e0e8c0', 'e': '#3a1a1a', 's': '#d68888',
};
export const FOREST_SPIRIT_FRAMES = [
  makeSprite(`
.....kkkk.......
....kgllllgk....
...kgllllllgk...
...kleelleelk...
...kllleelllk...
...kllllllllk...
...kgllllllgk...
...kggllllggk...
....kgggggk.....
.....kGGGGk.....
......kkkk......`, L_forestSpirit, 4),
  makeSprite(`
.....kkkk.......
....kgllllgk....
...kgllllllgk...
...klwwwwwwlk...
...klwwkkwwlk...
...klwwwwwwlk...
...kgllllllgk...
...kggllllggk...
....kgggggk.....
.....kGGGGk.....
......kkkk......`, L_forestSpirit, 4),
];

// 苔藓潜伏兽:蹲伏苔藓怪,两大眼 + 大嘴
const L_moss = {
  '.': null, 'k': PAL.black,
  'g': '#5a8a4a', 'G': '#2a3a2a', 'l': '#a0c890',
  'e': '#3a1a1a', 's': '#d68888', 'w': '#e0e8c0',
};
export const MOSS_LURKER_FRAMES = [
  makeSprite(`
....kkkkkkkk....
...kgllllllgk...
..kglllllllllgk
..kgllwwllwwgk.
..kglewkewkegk.
..kgllllllllgk.
..kgleeeeeelgk.
..kgllllllllgk.
..kggllllllggk.
..kggllllllggk.
...kgggggggk...
....kGGGGGGk...
.....kkkkkk....
`, L_moss, 4),
];

// 藤蔓幽魂:紫色幽灵,飘逸下摆 + 双眼 + 须
const L_vine = {
  '.': null, 'k': PAL.black,
  'v': '#7a5a8a', 'V': '#3a2a4a', 'l': '#c0a0d0',
  'e': '#1a0a1a', 'w': '#e0d0e0',
};
export const VINE_WRAITH_FRAMES = [
  makeSprite(`
......kkkk......
.....kvvvvk.....
....kvvvvvvk....
....kvwweewvk...
....kvwweewvk...
....kvvvvvvk....
....kvvvvvvk....
...kvvvvvvvvk...
...kvvvvvvvvk...
..kvvvvvvvvvvk..
..kvlvvvvvvlk...
..kvvvvvvvvvk...
..kvlvvvvvvlk...
...kkkkkkkkk....
`, L_vine, 4),
];

// 余烬小鬼:双角 + 大眼 + 嘴 + 火苗尾
const L_imp = {
  '.': null, 'k': PAL.black,
  'e': '#e87a3c', 'E': '#8a3a1a', 'l': '#ffc060',
  'y': '#e0b76a', 'w': '#fff0c0',
};
export const EMBER_IMP_FRAMES = [
  makeSprite(`
.k........k....
.kk........k...
.kEEkkkkEEK....
kEEEEEEEEEEk...
kEelllleelek...
kEewkeeewkek...
kEelllleelek...
kEeeeyyyyeEk...
kEeeeeeeeeEk...
.kEEEEEEEEk....
..kEEEEEEk.....
...kkkkkk......
....kllk.......
....kllk.......
`, L_imp, 4),
];

// 锻炉骑士:头盔(眼缝)+ 胸甲金纹 + 持剑
const L_knight = {
  '.': null, 'k': PAL.black,
  'i': '#5a5a66', 'I': '#2a2a30', 'g': '#e0b76a',
  'e': '#e87a3c', 'E': '#8a3a1a', 'l': '#ffc060',
};
export const FORGE_KNIGHT_FRAMES = [
  makeSprite(`
....kkkkkk......
...kIIIIIIk.....
..kIiiiiiiIk....
..kIiIIIIiIk....
..kIiIIIIiIk....
..kIiiiiiiIk....
...kIIIIIIk.....
..kiiiiiiiiik...
..kIiiiiiiiIk...
..kIigggggiIk...
..kIigggggiIk...
..kIiiiiiiiIk...
..kIIIIIIIIIk...
..kIiiiiiiIik...
..kIik..kIIk....
..kIik..kIIk....
...kkk..kkk....
..........l.....
`, L_knight, 4),
];

// 灰烬幻影:兜帽幽灵,飘逸 + 发光双眼
const L_phantom = {
  '.': null, 'k': PAL.black,
  'a': '#7a4a4a', 'A': '#3a1a1a', 'l': '#d68888',
  'e': '#1a0a0a', 'w': '#f4d8d8',
};
export const ASH_PHANTOM_FRAMES = [
  makeSprite(`
......kkkk......
.....kAAAAk.....
....kAAAAAAk....
...kAaaaaaaAk...
...kAawllaawk...
...kAaweeweawk..
...kAaaaaaaAk...
...kAaaaaaaAk...
..kAaaaaaaaaAk..
..kAaaaaaaaaAk..
..kAaaaaaaaaAk..
..kAlaaaaaalAk..
..kAlaaaaaalAk..
..kAaaaaaaaaAk..
..kAllaaaaallAk.
...kkkkkkkkkk...
`, L_phantom, 4),
];

// 墓园守卫:骷髅盔甲,空洞眼窝 + 鼻 + 牙嘴 + 持斧
const L_warden = {
  '.': null, 'k': PAL.black,
  'g': '#5a5a70', 'G': '#2a2a3a', 'l': '#a0a0c0',
  'e': '#1a0a1a', 'y': '#e0b76a', 'w': '#d6dce8',
};
export const GRAVE_WARDEN_FRAMES = [
  makeSprite(`
....kkkkkk......
...kGGGGGGGk....
..kGgggggggGk...
..kGgGGGGGgGk...
..kGgGeeeGgGk...
..kGgGeeeGgGk...
..kGgGyyyGgGk...
..kGgggggggGk...
..kGggeeeegGk...
..kGGGGGGGGGk...
..kGgggggggGk...
..kGgllllgGgk...
..kGgllllgGgk...
..kGgggggggGk...
..kGgk..kgGgk...
..kGGk..kGGk...
...kkk..kkk....
..........l.....
`, L_warden, 4),
];

// 墨水学者:尖帽法师 + 长袍 + 持书
const L_scholar = {
  '.': null, 'k': PAL.black,
  'i': '#4a3a6a', 'I': '#2a1a3a', 'l': '#8a7ab0',
  'e': '#0a0a0a', 'w': '#d6c8a4', 'g': '#e0b76a',
};
export const INK_SCHOLAR_FRAMES = [
  makeSprite(`
.......kk.......
......kIIk......
.....kIIIIk.....
....kIiiiiIk....
...kIiiiiiiIk...
...kIiiiiiiIk...
...kIweeeeelk...
...kIweeeeelk...
...kIwwwwwwIk...
...kIIIIIIIIk...
..kIiiiiiiiiIk..
..kIiggggggiIk..
..kIiiiiiiiiIk..
..kIiiiiiiiiIk..
..kIIIIIIIIIIk..
..kIik....kIIk..
...kkk....kkk...
..........w.....
`, L_scholar, 4),
];

// 寒霜潜伏兽:冰晶背脊 + 双眼 + 利嘴
const L_frost = {
  '.': null, 'k': PAL.black,
  'f': '#8aa9c4', 'F': '#4a6a8a', 'l': '#c4d8e8',
  'e': '#1a1a2a', 'w': '#ffffff',
};
export const FROST_LURKER_FRAMES = [
  makeSprite(`
....kkkkkkkk....
...kffllllffk...
..kfffllllfffk..
..kflwwllwwflk..
..kfleekleekfk..
..kffllllllffk..
..kfllllllllfk..
..kfeeeeeeeefk..
..kfllllllllfk..
..kffllllllffk..
...kffllllffk...
....kfffffffk...
.....kFFFFFk....
......kkkkk.....
`, L_frost, 4),
];

// 镜像骑士:银盔甲 + 镜面反光纹 + 持剑
const L_mirror = {
  '.': null, 'k': PAL.black,
  'm': '#a8b8d0', 'M': '#5a6a8a', 'l': '#e0e8f0',
  'e': '#1a1a2a', 'g': '#e0b76a',
};
export const MIRROR_KNIGHT_FRAMES = [
  makeSprite(`
....kkkkkk......
...kMMMMMMk.....
..kMmmmmmmMk....
..kMmlllllmk....
..kMmlllllmk....
..kMmmmmmmMk....
...kMMMMMMk.....
..kMmmmmmmmMk...
..kMmlmmmlmmk...
..kMmlmmmlmmk...
..kMmmmmmmmMk...
..kMmmmmmmmMk...
..kMMMMMMMMMk...
..kMmmmmmMmk....
..kMmk..kmMk....
..kMMk..kMMk....
...kkk..kkk.....
..........l.....
`, L_mirror, 4),
];

// 虚空追寻者:多眼 + 触手(诡异虚空生物)
const L_void = {
  '.': null, 'k': PAL.black,
  'v': '#3a2a4a', 'V': '#1a0a2a', 'l': '#b78ce0',
  'L': '#e0b0ff', 'e': '#0a0a0a', 'w': '#f4ecd0',
};
export const VOID_SEEKER_FRAMES = [
  makeSprite(`
......kkkk......
.....kvvvvk.....
....kvvvvvvk....
....kvLvvLvk....
....kvLvvLvk....
....kvvvvvvk....
...kvvvvvvvvk...
...kvLlvvLlvk...
...kvvvvvvvvk...
..kvvvvvvvvvvk..
..kvlvvvvvvvlk..
..kvvvvvvvvvvk..
..kvlvvvvvvvlk..
..kvvvvvvvvvvk..
...kkkkkkkkkk...
`, L_void, 4),
];
