// hero.js — 主角精灵帧(兜帽冒险者;按职业装配不同武器与配色)
// 结构:共享"无武器身体"网格 + 每职业武器单元表(stamp 到身体网格上)
//   recall 追忆者 = 紫光法杖(球) | forge 锻体者 = 宽刃巨剑 | weave 织梦者 = 星辉法杖
// 颜色(legend L):k 轮廓黑 / c 斗篷 / C 斗篷深 / s 皮肤 / L 面部辉光
//                 l 法杖光 / w 钢刃 / G 剑格金 / S 握柄缠皮
import { makeSprite, L } from './_tools.js';

// ===== 共享身体(无武器;18 列 × 21 行)=====
const BODY_IDLE = `
......kkkk........
.....kccccck......
....kccccccck.....
....kcsssssck.....
....kcskLksck.....
....kcsssssck.....
....kcsssssck.....
.....kccccck......
....cccccccc......
...cccccccccc.....
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..sccBBBBBBcc.s...
....cCCCCcc.......
....cc...cc.......
....bb...bb.......
....bb...bb.......
....kk...kk.......
..................
`;
const BODY_WALK1 = `
......kkkk........
.....kccccck......
....kccccccck.....
....kcsssssck.....
....kcskLksck.....
....kcsssssck.....
....kcsssssck.....
.....kccccck......
....cccccccc......
...cccccccccc.....
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..sccBBBBBBcc.s...
....cCCCCcc.......
...ccc...cc.......
...bbb...bb.......
...bbb...bb.......
...kkk...kk.......
..................
`;
const BODY_WALK2 = `
......kkkk........
.....kccccck......
....kccccccck.....
....kcsssssck.....
....kcskLksck.....
....kcsssssck.....
....kcsssssck.....
.....kccccck......
....cccccccc......
...cccccccccc.....
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..sccBBBBBBcc.s...
....cCCCCcc.......
....cc...ccc......
....bb...bbb......
....bb...bbb......
....kk...kkk......
..................
`;
// 攻击姿态(蓄力 → 三段连击):0 蓄力后仰 / 1 横扫前倾 / 2 上挑 / 3 劈砸
const BODY_WIND = `
......kkkk........
.....kccccck......
....kccccccck.....
...kcsssssck......
...kcskLksck......
...kcsssssck......
...kcsssssck......
.....kccccck......
....cccccccc......
..cccccccccc......
..cCCCCCCCCCC.....
..cCCCCCCCCCC.....
..cCCCCCCCCCC.....
..cCCCCCCCCCC.....
..ccBBBBBBcc......
...cCCCCcc........
..ccc...ccc.......
..bb.....bb.......
.bbb.....bbb......
.kkk.....kkk......
..................
`;
const BODY_SLASH = `
......kkkk........
.....kccccck......
....kccccccck.....
....kcsssssck.....
....kcskLksck.....
....kcsssssck.....
....kcsssssck.....
.....kccccck......
....cccccccc......
...cccccccc.......
...cCCCCCCC.......
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..sccBBBBBBcc.s...
....cCCCCcc.......
...ccc...cc.......
...bbb..bbb.......
...bbb..bbb.......
...kkk..kkk.......
..................
`;
const BODY_UPPER = `
......kkkk........
.....kccccck......
....kccccccck.....
....kcsssssck.....
....kcskLksck.....
....kcsssssck.....
....kcsssssck.....
.....kccccck......
....cccccccc......
...cccccccccc.....
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..sccBBBBBBcc.s...
....cCCCCcc.......
....cc...cc.......
....bb...bb.......
...bbb...bb.......
...kkk...kk.......
..................
`;
const BODY_SLAM = `
......kkkk........
.....kccccck......
....kccccccck.....
....kcsssssck.....
....kcskLksck.....
....kcsssssck.....
....kcsssssck.....
.....kccccck......
....cccccccc......
...cccccccccc.....
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..ccCCCCCCCCCCc...
..sccBBBBBBcc.s...
....cCCCCcc.......
....cc...ccc......
....bb...bbb......
....bb...bbb......
....kk...kkk......
..................
`;

const BODY = {
  idle: BODY_IDLE, walk1: BODY_WALK1, walk2: BODY_WALK2,
  wind: BODY_WIND, slash: BODY_SLASH, upper: BODY_UPPER, slam: BODY_SLAM,
};

// ===== 武器单元表([行, 列, 字符];叠印在身体网格上)=====
const vline = (r0, r1, col, ch) => {
  const out = [];
  for (let r = r0; r <= r1; r++) out.push([r, col, ch]);
  return out;
};

// 追忆者:紫光法杖(竖持,球在顶)
const STAFF_SIDE = [
  [3, 15, 'l'], [4, 15, 'l'],
  ...vline(5, 19, 15, 'k'),
  [20, 14, 'k'], [20, 15, 'k'],
];
const WEAPON_STAFF = {
  idle: STAFF_SIDE, walk1: STAFF_SIDE, walk2: STAFF_SIDE,
  wind: [
    [1, 16, 'L'], [2, 15, 'l'], [2, 16, 'l'], [3, 14, 'l'],
    [4, 14, 'k'], [5, 13, 'k'], [6, 12, 'k'], [7, 11, 'k'], [8, 11, 'k'],
  ],
  slash: [
    [9, 11, 'k'], [9, 12, 'k'], [9, 13, 'k'], [9, 14, 'k'],
    [9, 15, 'l'], [9, 16, 'l'],
  ],
  upper: [
    [0, 15, 'l'], [0, 16, 'l'], [1, 14, 'k'], [2, 13, 'k'], [3, 13, 'k'], [4, 13, 'k'],
  ],
  slam: [
    [7, 12, 'k'], [8, 12, 'k'], [9, 12, 'k'], [10, 12, 'k'],
    [11, 12, 'l'], [11, 13, 'l'], [12, 12, 'l'],
  ],
};

// 织梦者:星辉法杖(四芒星头 + 竖持)
const STAR_ORB = (r, c) => [[r - 1, c, 'w'], [r, c - 1, 'l'], [r, c, 'L'], [r, c + 1, 'l'], [r + 1, c, 'w']];
const WEAPON_STAR = {
  idle: [...STAR_ORB(3, 15), ...vline(5, 19, 15, 'k'), [20, 14, 'k'], [20, 15, 'k']],
  walk1: [...STAR_ORB(3, 15), ...vline(5, 19, 15, 'k'), [20, 14, 'k'], [20, 15, 'k']],
  walk2: [...STAR_ORB(3, 15), ...vline(5, 19, 15, 'k'), [20, 14, 'k'], [20, 15, 'k']],
  wind: [
    [0, 16, 'w'], [1, 15, 'l'], [1, 16, 'L'], [1, 17, 'l'], [2, 16, 'w'],
    [3, 14, 'k'], [4, 13, 'k'], [5, 13, 'k'], [6, 12, 'k'], [7, 11, 'k'], [8, 11, 'k'],
  ],
  slash: [
    [9, 11, 'k'], [9, 12, 'k'], [9, 13, 'k'],
    [8, 14, 'w'], [9, 14, 'L'], [10, 14, 'w'],
    [9, 15, 'l'],
  ],
  upper: [
    [0, 14, 'w'], [0, 16, 'w'], [1, 15, 'L'], [2, 15, 'l'],
    [2, 13, 'k'], [3, 13, 'k'], [4, 13, 'k'],
  ],
  slam: [
    [7, 12, 'k'], [8, 12, 'k'], [9, 12, 'k'], [10, 12, 'k'],
    [11, 12, 'L'], [11, 13, 'l'], [11, 11, 'l'], [12, 12, 'w'],
  ],
};

// 锻体者:宽刃巨剑(钢刃 w / 金格 G / 缠皮柄 S)
const SWORD_SIDE = [
  [4, 15, 'S'], [5, 15, 'S'],
  [6, 14, 'G'], [6, 15, 'G'], [6, 16, 'G'],
  ...vline(7, 19, 15, 'w'),
  [20, 15, 'w'],
];
const WEAPON_SWORD = {
  idle: SWORD_SIDE, walk1: SWORD_SIDE, walk2: SWORD_SIDE,
  wind: [
    [1, 16, 'w'], [2, 15, 'w'], [3, 14, 'w'],
    [4, 13, 'G'], [5, 12, 'S'],
  ],
  slash: [
    [9, 11, 'w'], [9, 12, 'w'], [9, 13, 'w'], [9, 14, 'w'], [9, 15, 'w'], [9, 16, 'w'], [9, 17, 'w'],
    [10, 10, 'G'], [10, 11, 'S'],
  ],
  upper: [
    [0, 16, 'w'], [1, 15, 'w'], [2, 14, 'w'], [3, 13, 'w'],
    [4, 13, 'G'], [4, 12, 'S'],
  ],
  slam: [
    [6, 12, 'S'], [7, 12, 'G'],
    ...vline(8, 15, 12, 'w'), [16, 12, 'w'],
  ],
};

// ===== 合成:身体 + 武器 → 帧 =====
function stampCells(grid, cells) {
  if (!cells || cells.length === 0) return grid;
  const rows = grid.split('\n');
  for (const [r, c, ch] of cells) {
    const i = r + 1; // 跳过开头空行
    const row = rows[i];
    if (row == null) continue;
    rows[i] = row.slice(0, c) + ch + row.slice(c + 1);
  }
  return rows.join('\n');
}

// 受击踉跄:闭眼(面部辉光熄灭)+ 帽顶左歪 1px —— 从待机体程序生成,武器随职业
// 注意:split('\n') 后索引 0 是模板串前导空行,内容行从 1 开始(与 stampCells 的 +1 约定一致)
const BODY_HURT_ROWS = BODY_IDLE.split('\n').map(r =>
  r.replaceAll('kLk', 'sss')
);
{
  // 帽顶整体左移 1px(6-9 列的 k 移到 5-8):从左往右逐像素搬,末列补透明
  const shift = (idx, from, to) => {
    const row = BODY_HURT_ROWS[idx];
    if (row == null || row[from] == null || row[to] == null) return;
    const ch = row[from];
    BODY_HURT_ROWS[idx] = row.slice(0, from) + '.' + row.slice(from + 1);
    const r2 = BODY_HURT_ROWS[idx];
    BODY_HURT_ROWS[idx] = r2.slice(0, to) + ch + r2.slice(to + 1);
  };
  shift(1, 6, 5); shift(1, 7, 6); shift(1, 8, 7); shift(1, 9, 8);
}
const BODY_HURT = BODY_HURT_ROWS.join('\n');

function buildFrames(weapon) {
  const spr = (name) => makeSprite(stampCells(BODY[name], weapon[name]), L, 4);
  return {
    idle: [spr('idle')],
    walk: [spr('walk1'), spr('walk2')],
    attack: [spr('wind'), spr('slash'), spr('upper'), spr('slam')],
    hurt: [makeSprite(stampCells(BODY_HURT, weapon.idle), L, 4)],
  };
}

export const HERO_FRAMES_RECALL = buildFrames(WEAPON_STAFF);
export const HERO_FRAMES_WEAVE = buildFrames(WEAPON_STAR);
export const HERO_FRAMES_FORGE = buildFrames(WEAPON_SWORD);

// 兼容旧导出(默认 = 追忆者)
export const HERO_FRAMES = HERO_FRAMES_RECALL;

// 供测试/工具:返回某职业某帧的合成网格字符串(无 canvas 依赖)
export function heroGridFor(cls, name) {
  const w = cls === 'forge' ? WEAPON_SWORD : cls === 'weave' ? WEAPON_STAR : WEAPON_STAFF;
  const body = name === 'hurt' ? BODY_HURT : (BODY[name] || BODY.idle);
  return stampCells(body, w[name] || w.idle);
}
